<?php
/**
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 * @var \Magento\Framework\View\TemplateEngine\Php $this
 */

$pcaSettings = $this->helper('PCAPredict\Addressy\Helper\SettingsData');
$pcaAccCode = $pcaSettings->getAccountCode();
$pcaCustomJSFront = $pcaSettings->getCustomJavaScriptFront() ?: '';

if (!$pcaAccCode) {
    return;
}

$script = <<<JavaScript

    requirejs(['jquery'], function(){

        (function() {
            if (typeof pca !== "undefined") {
                pca.magento.setupCheckout();
            }
        })();
    });
JavaScript;

echo $secureRenderer->renderTag('script', [], $script, false);
